// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Outloud.ScoreService.Persistance;

namespace Outloud.ScoreService.Migrations
{
    [DbContext(typeof(UserDataDbContext))]
    [Migration("20181227150837_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Outloud.ScoreService.Persistance.Models.CourseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("CourseId");

                    b.Property<string>("DisplayName");

                    b.Property<int>("Progress");

                    b.Property<string>("UserDataEntityId");

                    b.HasKey("Id");

                    b.HasIndex("UserDataEntityId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Outloud.ScoreService.Persistance.Models.UserDataEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("UserData");
                });

            modelBuilder.Entity("Outloud.ScoreService.Persistance.Models.CourseEntity", b =>
                {
                    b.HasOne("Outloud.ScoreService.Persistance.Models.UserDataEntity")
                        .WithMany("Courses")
                        .HasForeignKey("UserDataEntityId");
                });
#pragma warning restore 612, 618
        }
    }
}
